### ISSUE TITLE
Qt5.15 qml plugin issue

### ISSUE THREAD

**Issue by ParulRani** [torarnv/qmlcometd#1]
Hi,
I am not sure weather i am posting this issue on correct page but i found your contacts  from gut hub page for QT5.15.
I am building QT packages and using below  command line arguments for qtbase to create the  qmake.
 
sudo ./configure -libinput -bundled-xcb-xinput   -nomake examples   --prefix=/opt/Qt5.15.0

After performing all the steps for qtdeclarating just like qmake, make clean make -j4 I am not having the plugin.qmltypes for Layouts,windows ,QtQuick2 and for others.

But i can build every QT packages successfully so i tried that for my application that already working perfectly for Qt5.14 but for Qt5.15 its not working and i  got the error.
plugin cannot be loaded for module "QtQuick":Cannot load library libqtquick2plugin.so;undefine symbol:_z26qml_rgister_type_QtQuickv.

Please help .......

**Comment by torarnv** [comment]
Please report Qt issues upstream at https://bugreports.qt.io/
